/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.vrsoft.VRTesteUnitario;
import br.com.vrsoft.vrtesteunitario.App;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
